// Copyright (C) 1991-2012 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 12.1 (Build Build 177 11/07/2012)
// Created on Mon Feb 04 14:16:22 2013

fetch_unit fetch_unit_inst
(
	.1(1_sig) ,	// input  1_sig
	.branch(branch_sig) ,	// input  branch_sig
	.restart(restart_sig) ,	// input  restart_sig
	.clock(clock_sig) ,	// input  clock_sig
	.instr(instr_sig) 	// output  instr_sig
);

